function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 18-Apr-2012 15:50:34

% Create legend
legend1 = legend('U','V'axes1,'show');

set(legend1,'Units','pixels');

